name: 'move-tasks'
description: 'Github action to move tasks on Github projects'
author: 'Hung Luu <hungluu2106@gmail.com>'
inputs:
  actionToken:
    required: true
    description: 'Github token with required permissions on Projects & Issues'
  project:
    required: true
    description: 'number id or name of project to move tasks into'
  repository:
    required: true
    description: 'owner/repo-name'
  fromCards:
    required: true
    description: 'instruction to find cards to move'
  toColumn:
    required: true
    description: 'instruction to find column for moving cards into'
runs:
  using: 'node16'
  main: 'action/index.js'
branding:
  icon: 'truck'
  color: 'green'
